github: kashsightplatform
ko_fi: kashsightplatform
custom:
  - https://paypal.me/kashsightplatform
  - https://selar.co/kashsightplatform
  - mailto:kashsightplatform@gmail.com?subject=kslearn%20Donation
